name: Run RPA
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Install-Packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - run: echo "ğŸ This job's status is ${{ job.status }}."
