name: Run RPA
run-name: ${{ github.actor }} is running some tests ðŸš€
on:
  push:
    branches:
      - main
      - locust

  schedule:
    - cron: "0 6 * * *"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Locust
        run: |
          locust --headless --users 2
      - name: Check out repository code
        uses: actions/checkout@v4