name: Run RPA
run-name: ${{ github.actor }} is running some tests ðŸš€
on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Database setup
        run: |
          python Track_RPA/Set_Database.py
      - name: Run tests
        run: |
          DIRECTORY="Track_RPA/tests"

          for file in $DIRECTORY/*; do
            if [[ -f "$file" ]]; then
              python "$file"
            fi
          done
      - name: Get current date
        id: DATE
        run: echo "{DATE}=$(date +'%m%d%YT%H%M%S')" >> $GITHUB_ENV
      - name: Show Current date
        run: echo "$(date +'%m%d%YT%H%M%S')"
      - name: Rename PDF
        run: mv Track_RPA/Archives/Detailed/Track_Validation.pdf Track_RPA/Archives/Detailed/Track_Validation_${{ env.DATE }}.pdf
      - name: Show PDF folder
        run: ls Track_RPA/Archives/Detailed/
      - name: Upload PDF
        uses: yakubique/minio-upload@v1.1.3
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_BUCKET }}
          source: 'Track_RPA/Archives/Detailed/Track_Validation_${{ env.DATE }}.pdf'
          target: '/'
      - name: Check out repository code
        uses: actions/checkout@v4