name: Run RPA
run-name: ${{ github.actor }} is running some tests ðŸš€
on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 6 * * *"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Set up NPM
        uses: actions/setup-node@v4
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Lighthouse
        run: |
          npm i -g lighthouse
      - name: Run tests
        run: |
          behave --format json --outfile report/output/results.json
      - name: Run bot
        if: success() || failure()
        run: |
          python report/bot.py
      - name: Generate PDF file
        if: success() || failure()
        run: |
          python report/generate_pdf.py
      - name: Get current date
        if: success() || failure()
        id: DATE
        run: echo "DATE=$(date +'%m%d%YT%H%M%S')" >> $GITHUB_ENV
      - name: Rename PDF
        if: success() || failure()
        run: mv report/output/Track_Validation.pdf report/output/Track_Validation_${{ env.DATE }}.pdf
      - name: Rename Results JSON
        if: success() || failure()
        run: mv report/output/results.json report/output/results_${{ env.DATE }}.json
      - name: Upload Folder
        if: success() || failure()
        uses: yakubique/minio-upload@v1.1.3
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_BUCKET }}
          source: 'report/output/*'
          target: '/'
